[als.webcam]
video = 0
thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"

[[keyboard]]
name = "keyboard-thinkpad"
path = "/sys/bus/platform/devices/thinkpad_acpi/leds/tpacpi::kbd_backlight"
